source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'TaylorSource' do
  pod 'YapDatabaseExtensions', '~> 1.5.0'
end

target 'TaylorSourceTests' do
  pod 'YapDatabaseExtensions', '~> 1.5.0'
end

