source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'TaylorSource' do
  pod 'YapDatabaseExtensions'
end

target 'TaylorSourceTests' do
  pod 'YapDatabaseExtensions'
  pod 'Quick', '0.3'
  pod 'Nimble', '1.0.0-rc.1'  
end

