source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

platform :ios, "8.0"

target 'Datasources' do
  pod 'DateTools'
  pod 'TaylorSource/YapDatabase', :path => '../../'
end

target 'DatasourcesTests' do
  pod 'DateTools'
  pod 'TaylorSource/YapDatabase', :path => '../../'
end
