inhibit_all_warnings!
use_frameworks!

platform :ios, "8.0"

target 'Datasources' do

  pod 'DateTools'
  pod 'YapDatabaseExtensions', :git => 'https://github.com/danthorpe/YapDatabaseExtensions.git', :branch => 'swift_2.0'
  pod 'TaylorSource/YapDatabase', :path => '../../'

end

