source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

platform :ios, "8.0"

target 'Datasources' do

  pod 'DateTools'
  pod 'YapDatabaseExtensions', '~> 2'
  pod 'TaylorSource/YapDatabase', :path => '../../'

end
