before_all {
    carthage(platform: "iOS")
}

lane :lint do

    swiftLint(
        mode: :lint, 
        config_file: '.swiftlint.yml'
    )
end

desc "Runs all the tests"
lane :test do

	scan(
	  scheme: "TaylorSource",
	  code_coverage: true,
	  output_directory: ".ci/xcodebuild-data",
	  xcargs: "-derivedDataPath .ci/xcodebuild-data"
	)

end
